### ISSUE TITLE
PostgreSQL Broken

### ISSUE THREAD

**Issue by OverlordQ** [zikula/core#2036]
Can't even get past the install since even the installer is broken.

First the `install/templates/plugins/function.dbtypes.php` is referring to the Postgres driver as postgres instead of pgsql, secondly once that's fixed, it can't even install the DB schema:

```Uncaught exception SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "Array"
LINE 1: CREATE UNIQUE INDEX areaidx ON hook_area (Array)
                                                  ^. Failing Query: "CREATE UNIQUE INDEX areaidx ON hook_area (Array)". Failing Query: CREATE UNIQUE INDEX areaidx ON hook_area (Array) in /www/tg.com/html/lib/vendor/Doctrine/Doctrine/Export.php line, 1219
#0 /www/tg.com/html/lib/vendor/Doctrine/Doctrine/Core.php(910): Doctrine_Export->exportClasses(Array)
#1 /www/tg.com/html/system/Extensions/lib/Extensions/Installer.php(45): Doctrine_Core::createTablesFromArray(Array)
#2 /www/tg.com/html/install/lib.php(433): Extensions_Installer->install()
#3 /www/tg.com/html/install/lib.php(252): installmodules('en')
#4 /www/tg.com/html/install.php(20): install(Object(Zikula_Core))
#5 {main}```

**Comment by craigh** [comment]
closed by #3783
