### ISSUE TITLE
file permissions in tar.gz not correct

### ISSUE THREAD

**Issue by rallek** [zikula/core#2265]
I downloaded the RC1 files from http://zikula.org/library/releases

Uploaded to allinkl shared service (with command line access). unpacked by tar -xvzf

here is the result of ls:
````
ssh-w012e56e@dd34716:/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app$ ls -lisa
total 48
71540887 4 drwxr-xr-x  7 ssh-w012e56e w012e56e 4096 Feb 21 15:43 .
71344275 4 drwxr-xr-x 16 ssh-w012e56e w012e56e 4096 Feb 21 15:44 ..
71456076 4 -rw-r--r--  1 ssh-w012e56e w012e56e  537 Feb 21 15:43 autoload.php
71549075 4 drwxr-xr-x  2 ssh-w012e56e w012e56e 4096 Feb 21 15:45 cache
71549090 4 drwxr-xr-x  3 ssh-w012e56e w012e56e 4096 Feb 21 15:43 config
71456093 4 -rw-r--r--  1 ssh-w012e56e w012e56e  649 Feb 21 15:43 console
71549076 4 drwxr-xr-x  3 ssh-w012e56e w012e56e 4096 Feb 21 15:43 custom
71456077 4 -rw-r--r--  1 ssh-w012e56e w012e56e   13 Feb 21 15:43 .htaccess
71540895 4 drwxr-xr-x  2 ssh-w012e56e w012e56e 4096 Feb 21 15:45 logs
71540896 4 drwxr-xr-x  5 ssh-w012e56e w012e56e 4096 Feb 21 15:43 Resources
71456094 8 -rw-r--r--  1 ssh-w012e56e w012e56e 4631 Feb 21 15:43 ZikulaKernel.php
ssh-w012e56e@dd34716:/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app$ cd logs
ssh-w012e56e@dd34716:/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/logs$ ls -lisa
total 12
71540895 4 drwxr-xr-x 2 ssh-w012e56e w012e56e 4096 Feb 21 15:45 .
71540887 4 drwxr-xr-x 7 ssh-w012e56e w012e56e 4096 Feb 21 15:43 ..
71456075 4 -rw-r--r-- 1 ssh-w012e56e w012e56e   31 Feb 21 15:43 .htaccess
ssh-w012e56e@dd34716:/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/logs$
````

Calling my site I do get the error message:

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/cache/prod) ' in /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:609 Stack trace: #0 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(533): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php(306): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(128): Zikula\Bundle\CoreBundle\HttpKernel\ZikulaKernel->initializeContainer() #3 /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php(85): Symfony\Component\HttpKernel\Kernel-> in /www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 609

I will change the permission of this folder (app/cache and app/logs)  and proceed in testing

**Comment by rallek** [comment]
next problem:

after changing cache and logs to 777 I see the install screen. Clicking on the install button I do get this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Failed to copy "/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/config/parameters.yml" to "/www/htdocs/w012e56e/rallek.k62.org/Zikula_Core-1.4.0/app/config/custom_parameters.yml" because target file could not be opened for writing.

co I made the app/config folder also 777

**Comment by rallek** [comment]
Now the installer is showing again. Unexpected the folders /app/config/dynamic /userdata and /config are not writable. 

I manually change the permissions as well

**Comment by rallek** [comment]
Stop! 

I do have a problem in Ownership! The owner of the files must be www-run. But If I upload the tar.gz file and unpack it by my ssh-owner the files will have the ownership of the ssh-owner. I will restart the test, unpack again and change the ownership of the unpacked files first.

**Comment by rallek** [comment]
while waiting for the change ownership of all files I am thinking about this problem. A lot of user only can use ftp because they are on shared hosting. They are not able to change the ownership to the webserver (PHP-User is the name at allinkl). So the normal shared hosting user will have trouble to install.

**Comment by rallek** [comment]
after changing the ownership of all files the installation is running well
