### ISSUE TITLE
Install of ci build 79 fails "Failed to chmod file "/var/lib/jenkins/jobs/Zikula_Core-1.4.2/workspace/build/export/Zikula_Core-1.4.2/app/cache/prod/ztemp/doctrinemodels"

### ISSUE THREAD

**Issue by rallek** [zikula/core#2748]
Warning: mkdir(): Permission denied in /home/www/142.koester123.de/Zikula_Core-1.4.2/lib/legacy/util/FileUtil.php on line 275

```
Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to chmod file "/var/lib/jenkins/jobs/Zikula_Core-1.4.2/workspace/build/export/Zikula_Core-1.4.2/app/cache/prod/ztemp/doctrinemodels".' in /home/www/142.koester123.de/Zikula_Core-1.4.2/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:196 Stack trace:
#0 /home/www/142.koester123.de/Zikula_Core-1.4.2/lib/legacy/util/FileUtil.php(277): Symfony\Component\Filesystem\Filesystem->chmod('/var/lib/jenkin...', 511, 0, true)
#1 /home/www/142.koester123.de/Zikula_Core-1.4.2/lib/legacy/util/CacheUtil.php(57): FileUtil::mkdirs('/var/lib/jenkin...', 511, true)
#2 /home/www/142.koester123.de/Zikula_Core-1.4.2/lib/Zikula/Bundle/CoreBundle/EventListener/Doctrine1ConnectorListener.php(84): CacheUtil::createLocalDir('doctrinemodels')
#3 [internal function]: Zikula\Bundle\CoreBundle\EventListener\Doctrine1ConnectorListener->doctrineInit(Object(Zikula\Core\Event\GenericEvent), 'doctrine.init_c...', Object(Zikula_EventM in /home/www/142.koester123.de/Zikula_Core-1.4.2/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 196
```

**Comment by craigh** [comment]
please delete every thing and try build 73 http://ci.zikula.org/job/Zikula_Core-1.4.2/73/

**Comment by rallek** [comment]
That works fine

**Comment by craigh** [comment]
please now test build 80.

**Comment by craigh** [comment]
ping @rallek

**Comment by rallek** [comment]
today I am back home. ci build 88 is installing fine

**Comment by craigh** [comment]
:+1:
